# Generated by Django 5.0.3 on 2024-03-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "snippet_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("snippet", models.TextField()),
            ],
        ),
    ]
