# Generated by Django 5.0.3 on 2024-03-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shareme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="encrypted",
            field=models.BooleanField(default=False),
        ),
    ]
