# Generated by Django 5.0.3 on 2024-03-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shareme", "0002_snippet_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="salt",
            field=models.BinaryField(default=None, max_length=16),
        ),
    ]
