# Generated by Django 5.0.3 on 2024-03-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shareme", "0003_snippet_salt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="salt",
            field=models.BinaryField(default=None, max_length=16, null=True),
        ),
    ]
