# Generated by Django 5.0.3 on 2024-03-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "short_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("long_url", models.TextField()),
            ],
        ),
    ]
